apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isnarmesteleder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 600m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 384Mi
  ingresses:
    - "https://isnarmesteleder.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomoteadmin
          namespace: teamsykefravr
          cluster: prod-fss
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "isproxy.prod-fss-pub.nais.io"
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "syfo-tilgangskontroll.prod-fss-pub.nais.io"
      rules:
        - application: isnarmesteleder-redis
  azure:
    application:
      enabled: true
      tenant: nav.no
  envFrom:
    - secret: isnarmesteleder-redis-password
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: isnarmesteleder-db
        diskAutoresize: true
  kafka:
    pool: nav-prod
  env:
    - name: KTOR_ENV
      value: "production"
    - name: ISPROXY_CLIENT_ID
      value: "prod-fss.teamsykefravr.isproxy"
    - name: ISPROXY_URL
      value: "https://isproxy.prod-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "prod-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: SYFOTILGANGSKONTROLL_URL
      value: "https://syfo-tilgangskontroll.prod-fss-pub.nais.io"
    - name: REDIS_HOST
      value: "isnarmesteleder-redis.teamsykefravr.svc.cluster.local"
