apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isnarmesteleder
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isnarmesteleder.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-fss
        - application: oppfolgingsplan-backend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: syfomotebehov
          namespace: team-esyfo
          cluster: dev-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isoppfolgingstilfelle
          namespace: teamsykefravr
          cluster: dev-gcp
    outbound:
      external:
        - host: "login.microsoftonline.com"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
        - application: isnarmesteleder-redis
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  tokenx:
    enabled: true
  envFrom:
    - secret: isnarmesteleder-redis-password
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - name: isnarmesteleder-db
        diskAutoresize: true
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: "production"
    - name: EREG_URL
      value: "https://ereg-services-q1.dev-fss-pub.nais.io"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: REDIS_HOST
      value: "isnarmesteleder-redis.teamsykefravr.svc.cluster.local"
