ALTER TABLE NARMESTE_LEDER_RELASJON
DROP COLUMN referanse_uuid;

ALTER TABLE NARMESTE_LEDER_RELASJON
ADD COLUMN referanse_uuid VARCHAR(50) NOT NULL;

ALTER TABLE NARMESTE_LEDER_RELASJON
DROP COLUMN timestamp;

ALTER TABLE NARMESTE_LEDER_RELASJON
ADD COLUMN timestamp timestamptz NOT NULL UNIQUE;
